import { addInventoryRecord } from "./inventory";
import { getHuman, moveHuman } from "./humans";
import { listModules } from "./modules";
import { readData, writeData } from "./storage";
import { observeAlert, resolveAlert } from "./alerts";
import { ExplorationState } from "./types";
const CAPACITY_KG = 20, SUIT_BATTERY = 100, SUIT_OXYGEN = 100, BATTERY_PER_TICK = 2, OXYGEN_PER_TICK = 3;
export function getEvaStatus(): ExplorationState { return readData().exploration ?? { humanId: null, x: 0, y: 0, carried: {}, capacityKg: CAPACITY_KG, battery: SUIT_BATTERY, batteryCapacity: SUIT_BATTERY, batteryPerTick: BATTERY_PER_TICK, oxygen: SUIT_OXYGEN, oxygenCapacity: SUIT_OXYGEN, oxygenPerTick: OXYGEN_PER_TICK }; }
export function ensureEvaOperational(state = getEvaStatus()): void { if (state.humanId && (state.battery <= 0 || state.oxygen <= 0)) throw new Error("EVA is exhausted; the explorer did not return in time."); }
function suitport() { const module = listModules().find((m) => m.capabilities.includes("suitport-access") || m.blueprintId === "basic-suitport"); if (!module) throw new Error("No basic suitport is available."); return module; }
export function deployExplorer(humanId: string): ExplorationState { const current = getEvaStatus(); if (current.humanId) throw new Error("A human is already deployed."); const human = getHuman(humanId), port = suitport(); if (human.locationModuleId !== port.id) throw new Error("Human must be in the active suitport to deploy."); const next = { humanId, x: 0, y: 0, carried: {}, capacityKg: CAPACITY_KG, battery: SUIT_BATTERY, batteryCapacity: SUIT_BATTERY, batteryPerTick: BATTERY_PER_TICK, oxygen: SUIT_OXYGEN, oxygenCapacity: SUIT_OXYGEN, oxygenPerTick: OXYGEN_PER_TICK }; writeData({ ...readData(), exploration: next }); observeAlert("eva-deployed", "warning", "eva", humanId); return next; }
export function moveExplorer(x: number, y: number): ExplorationState { const state = getEvaStatus(); if (!state.humanId) throw new Error("No human is deployed."); ensureEvaOperational(state); if (!Number.isInteger(x) || !Number.isInteger(y) || Math.abs(x - state.x) + Math.abs(y - state.y) !== 1) throw new Error("EVA moves must be one adjacent cardinal tile."); const next = { ...state, x, y }; writeData({ ...readData(), exploration: next }); return next; }
export function addCarried(resourceId: string, quantityKg: number): ExplorationState { const state = getEvaStatus(); if (!state.humanId) throw new Error("No human is deployed."); ensureEvaOperational(state); const total = Object.values(state.carried).reduce((sum, value) => sum + value, 0); if (!Number.isInteger(quantityKg) || quantityKg <= 0) throw new Error("Collection quantity must be a positive whole number."); if (total + quantityKg > state.capacityKg) throw new Error("Collection would exceed EVA carrying capacity."); const next = { ...state, carried: { ...state.carried, [resourceId]: (state.carried[resourceId] ?? 0) + quantityKg } }; writeData({ ...readData(), exploration: next }); if (total + quantityKg === state.capacityKg) observeAlert("eva-capacity", "warning", "eva", state.humanId); return next; }
export function dockExplorer(): ExplorationState { const state = getEvaStatus(); if (!state.humanId) throw new Error("No human is deployed."); ensureEvaOperational(state); if (state.x !== 0 || state.y !== 0) throw new Error("Explorer must return to (0, 0) before docking."); const port = suitport(); moveHuman(state.humanId, port.id); addInventoryRecord(state.carried); const next = { ...state, humanId: null, x: 0, y: 0, carried: {} }; writeData({ ...readData(), exploration: next }); resolveAlert("eva-deployed"); resolveAlert("eva-capacity"); return next; }
export function drainEvaForTicks(state: ExplorationState, ticks: number): ExplorationState { if (!state.humanId) return state; return { ...state, battery: Math.max(0, state.battery - state.batteryPerTick * ticks), oxygen: Math.max(0, state.oxygen - state.oxygenPerTick * ticks) }; }
